sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t andersontmp/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true andersontmp/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "sa-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-sa-east-1-267387660376"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY