sudo: required
services:
  - docker

before_install:
  - docker build -t andersontmp/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true andersontmp/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-267387660376"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"