sudo: required
services:
  - docker

before_install:
  - docker build -t andersontmp/docker-react -f Dockerfile.dev .

scripts:
  - docker run andersontmp/docker-react npm run test -- --coverage